#!/usr/bin/env bun
/**
 * PI FRONT DOOR — open the same LifeOS install from the Pi coding agent.
 *
 *   bun Mount.ts [mount]   managed LifeOS block → ~/.pi/agent/APPEND_SYSTEM.md (appended
 *                          to Pi's system prompt — outranks AGENTS.md), skills synced to
 *                          ~/.pi/agent/skills (Pi wants kebab `name:`; matched by
 *                          frontmatter name like PiSync.sh v2), and the generated shim
 *                          ~/.pi/agent/extensions/lifeos-bridge.ts (hook bridge)
 *   bun Mount.ts status
 *   bun Mount.ts unmount
 *
 * The shim maps Pi's events onto LifeOS hooks through PI/Bridge.ts:
 *   session_start      → SessionStart   (context held for the first run)
 *   before_agent_start → UserPromptSubmit (Router line + directive appended to the system prompt)
 *   tool_call          → PreToolUse     ({ block, reason } when a guard says no)
 *   tool_result        → PostToolUse
 *   agent_end          → Stop
 */

import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "fs";
import { join } from "path";
import { homedir } from "os";
import { doorContext, removeManaged, writeManaged } from "../TOOLS/lib/DoorContext";

const PI = process.env.PI_AGENT_DIR ?? join(homedir(), ".pi", "agent");
const CLAUDE = process.env.LIFEOS_CLAUDE_DIR ?? join(homedir(), ".claude");
const BRIDGE = join(CLAUDE, "LIFEOS", "PI", "Bridge.ts");
const SHIM = join(PI, "extensions", "lifeos-bridge.ts");
const MARK = "lifeos-managed: true";

const kebab = (n: string) => n.replace(/^_/, "").replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();

function syncSkills(): number {
  const src = join(CLAUDE, "skills");
  if (!existsSync(src)) return 0;
  let n = 0;
  for (const name of readdirSync(src)) {
    const skill = join(src, name, "SKILL.md");
    if (!existsSync(skill)) continue;
    const dst = join(PI, "skills", kebab(name));
    const existing = join(dst, "SKILL.md");
    if (existsSync(existing) && !readFileSync(existing, "utf-8").includes(MARK)) continue; // principal's own Pi skill — leave it
    mkdirSync(dst, { recursive: true });
    const body = readFileSync(skill, "utf-8").replace(/^---\n([\s\S]*?)\n---/, (_m, fm: string) =>
      `---\n${fm.replace(/^name:.*$/m, `name: ${kebab(name)}`)}\n${MARK}\nsource: ${skill}\n---`);
    writeFileSync(existing, body);
    n++;
  }
  return n;
}

function removeSkills(): number {
  const dir = join(PI, "skills");
  if (!existsSync(dir)) return 0;
  let n = 0;
  for (const name of readdirSync(dir)) {
    const f = join(dir, name, "SKILL.md");
    if (existsSync(f) && readFileSync(f, "utf-8").includes(MARK)) { rmSync(join(dir, name), { recursive: true }); n++; }
  }
  return n;
}

export function shimSource(bridgePath: string): string {
  return `// GENERATED by LIFEOS/PI/Mount.ts — do not edit; re-run Mount.ts instead.
// Bridges Pi's extension events onto LifeOS's hooks (Router/Jev, Safety, capture).
import { spawnSync } from "node:child_process";

const BRIDGE = ${JSON.stringify(bridgePath)};
type Verdict = { additionalContext: string[]; block: { reason: string } | null };

function bridge(event: string, payload: Record<string, unknown>): Verdict {
  try {
    const r = spawnSync("bun", [BRIDGE, event], { input: JSON.stringify(payload), encoding: "utf-8", timeout: 15000 });
    return JSON.parse(r.stdout || "{}") as Verdict;
  } catch {
    return { additionalContext: [], block: null }; // fail open, like the Claude hooks
  }
}

export default function (pi: any) {
  let sessionId = "pi-" + Date.now();
  let pending: string[] = [];

  pi.on("session_start", async (_event: any, ctx: any) => {
    pending = bridge("SessionStart", { session_id: sessionId, cwd: ctx?.cwd }).additionalContext ?? [];
  });

  pi.on("before_agent_start", async (event: any, ctx: any) => {
    const prompt = typeof event?.prompt === "string" ? event.prompt : String(event?.input ?? "");
    const v = bridge("UserPromptSubmit", { session_id: sessionId, cwd: ctx?.cwd, prompt });
    const extra = [...pending, ...(v.additionalContext ?? [])].join("\\n\\n");
    pending = [];
    if (!extra) return;
    // Append, never replace: Pi's own prompt stays intact.
    if (typeof event?.systemPrompt === "string") return { systemPrompt: event.systemPrompt + "\\n\\n" + extra };
    ctx?.ui?.notify?.(extra.split("\\n")[0]);
  });

  pi.on("tool_call", async (event: any, ctx: any) => {
    const v = bridge("PreToolUse", { session_id: sessionId, cwd: ctx?.cwd, tool_name: event?.toolName, tool_input: event?.input ?? event?.args ?? {} });
    if (v.block) return { block: true, reason: v.block.reason };
  });

  pi.on("tool_result", async (event: any, ctx: any) => {
    bridge("PostToolUse", { session_id: sessionId, cwd: ctx?.cwd, tool_name: event?.toolName, tool_input: event?.input ?? {}, tool_response: event?.result ?? null });
  });

  pi.on("agent_end", async (_event: any, ctx: any) => {
    bridge("Stop", { session_id: sessionId, cwd: ctx?.cwd });
  });
}
`;
}

if (import.meta.main) {
  const cmd = process.argv[2] ?? "mount";
  if (cmd === "mount") {
    mkdirSync(join(PI, "extensions"), { recursive: true });
    writeManaged(join(PI, "APPEND_SYSTEM.md"), doorContext("pi"));
    const n = syncSkills();
    writeFileSync(SHIM, shimSource(BRIDGE));
    console.log(`Pi front door mounted at ${PI}: APPEND_SYSTEM.md block, ${n} skill(s), extension shim ${SHIM}`);
  } else if (cmd === "unmount") {
    removeManaged(join(PI, "APPEND_SYSTEM.md"));
    const n = removeSkills();
    if (existsSync(SHIM)) rmSync(SHIM);
    console.log(`unmounted: block removed, ${n} managed skill(s) removed, shim removed`);
  } else if (cmd === "status") {
    const block = existsSync(join(PI, "APPEND_SYSTEM.md")) && readFileSync(join(PI, "APPEND_SYSTEM.md"), "utf-8").includes("LIFEOS:BEGIN");
    const skills = existsSync(join(PI, "skills")) ? readdirSync(join(PI, "skills")).filter((d) => { const f = join(PI, "skills", d, "SKILL.md"); return existsSync(f) && readFileSync(f, "utf-8").includes(MARK); }).length : 0;
    console.log(JSON.stringify({ piDir: PI, appendSystemBlock: block, managedSkills: skills, shim: existsSync(SHIM) }, null, 2));
  } else {
    console.error("usage: Mount.ts [mount|status|unmount]");
    process.exit(2);
  }
}
