#!/usr/bin/env bash
# Create the open-work issues from open-issues.json with the gh CLI.
# Requires Issues enabled on the repo (Settings → General → Features → Issues).
#   bash create-issues.sh [owner/repo]        default: mrkingsleyobi/LifeOS
# The first entry is the tracking issue; every other issue links back to it.
set -euo pipefail
# ALREADY FILED on 2026-10-09 as mrkingsleyobi/LifeOS#8 (tracking) + #9–#29.
# Re-running creates duplicates; pass --force only for a different repo.
if [[ "${1:-}" != */* || "${2:-}" != "--force" ]] && [[ "${1:-mrkingsleyobi/LifeOS}" == "mrkingsleyobi/LifeOS" ]]; then
  echo "already filed as mrkingsleyobi/LifeOS#8–#29; refusing to duplicate" >&2; exit 1
fi
REPO="${1:-mrkingsleyobi/LifeOS}"
FILE="$(dirname "$0")/open-issues.json"
FOOTER=$'\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_'

track_title=$(jq -r '.[0].title' "$FILE")
track_url=$(gh issue create -R "$REPO" --title "$track_title" --body "$(jq -r '.[0].body' "$FILE")$FOOTER")
track_no="${track_url##*/}"
echo "tracking: $track_url"

children=""
n=$(jq 'length' "$FILE")
for ((i = 1; i < n; i++)); do
  title=$(jq -r ".[$i].title" "$FILE")
  body="$(jq -r ".[$i].body" "$FILE")"$'\n\nPart of #'"$track_no$FOOTER"
  url=$(gh issue create -R "$REPO" --title "$title" --body "$body")
  echo "  $url"
  children+="- [ ] #${url##*/} ${title}"$'\n'
done

# Checklist of sub-issues on the tracking issue.
gh issue edit "$track_no" -R "$REPO" --body "$(jq -r '.[0].body' "$FILE")"$'\n\n## Sub-issues\n'"$children$FOOTER"
echo "done: $((n - 1)) issues under #$track_no"
